### ISSUE TITLE
DownloadController missing IndexAction in book text.

### ISSUE THREAD

**Issue by ghost** [olegkrivtsov/using-zf3-book-samples#1]
Hi,

When I compared DownloadController found at using-zf3-book-samples/helloworld/module/Application/src/Controller/DownloadController.php to the DownloadController found in the books text in chapter 4.15 I found that the DownloadController in the book was missing its IndexAction().

Also the stated URL in the book is also incorrect. For me the URL "http://localhost/public/download/file?name=sample.txt" gave the desired result.

Thank you again for your book.

**Comment by olegkrivtsov** [comment]
Hi @Farsideman 

> When I compared DownloadController found at using-zf3-book-samples/helloworld/module/Application/src/Controller/DownloadController.php to the DownloadController found in the books text in chapter 4.15 I found that the DownloadController in the book was missing its IndexAction().

This is by design, not a mistake. Actually, samples may contain more code than I describe in the book. Some code is obvious and simple, and I don't describe it in the chapter.

> Also the stated URL in the book is also incorrect. For me the URL "http://localhost/public/download/file?name=sample.txt" gave the desired result.

Probably, you configured your virtual host incorrectly or didn't enable `mod_rewrite` module. `public` shouldn't be in the URL.

**Comment by olegkrivtsov** [comment]
Closing this as there is no response from the reporter.
