### ISSUE TITLE
Blog - there's no form validation on the 'status' field

### ISSUE THREAD

**Issue by olegkrivtsov** [olegkrivtsov/using-zf3-book-samples#37]
Reported by David Garcia a day ago via Disqus:

> I'm surprised there's no form validation on the 'status' field. What if someone edits the select list value using the client side development tools and then submits the form. Any range of values can be submitted but they won't be validated in this case. Just copy the 'title' field validation and modify.

**Comment by david-garcia-nete** [comment]
$inputFilter->add([
                    'name'     => 'status',
                    'required' => true,            
                    'validators' => [
                        [
                            'name'    => 'InArray',
                            'options'=> [
                                'haystack' => [Post::STATUS_PUBLISHED, Post::STATUS_DRAFT],
                            ]    
                        ],
                    ],
                ]);

**Comment by olegkrivtsov** [comment]
Fixed

**Comment by shaunfreeman** [comment]
The Select element enables a default inArray filter by default, so adding the input filter for status is unnecessary here unless you add the option 'disable_in_array_validator' to the select element and customise the validation and since you're not filtering this element, this is just repeating code already written in the Select element.  So doing it this way this is duplication and a waste of typing in my opinion.Take a look at the code https://github.com/zendframework/zend-form/blob/4419eef6dbe9d276e7e27c6a25f022be74534959/src/Element/Select.php#L219

**Comment by david-garcia-nete** [comment]
You’re right.  Thanks for pointing that out Shaun. My mistake Oleg.

**Comment by olegkrivtsov** [comment]
Hi @david-garcia-nete @shaunfreeman well spotted!

**Comment by olegkrivtsov** [comment]
Fixed.
